/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static org.junit.Assert.*;

import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;

import org.junit.Test;
import org.openimaj.image.ImageUtilities;
import org.openimaj.image.MBFImage;

import imagesearch.NotCompatibleException;

public class ComparatorTest extends AbstractTestWithImages{
    private static final double DELTA = 0.1;

	@Test 
    public void testCompareSameImage() throws IOException, NotCompatibleException {
		double result = compare(PATH+"1.jpg",PATH+"1.jpg");
    	assertEquals(0.0,result,DELTA);
    }
	
	@Test
	public void testCompareDifferentImage() throws IOException, NotCompatibleException {
		double result = compare(PATH+"1.jpg",PATH+"2.jpg");
		assertNotEquals(0.0, result, DELTA);
	}
	
	
}
